### ISSUE TITLE
snap failing to load python3-cryptography

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#326]
On dists other than Focal I get:

Traceback (most recent call last):
  File "/snap/hotsos/460/bin/hotsos", line 5, in <module>
    from hotsos.cli import main
  File "/snap/hotsos/460/lib/python3.8/site-packages/hotsos/cli.py", line 16, in <module>
    from hotsos.client import HotSOSClient, PLUGIN_CATALOG
  File "/snap/hotsos/460/lib/python3.8/site-packages/hotsos/client.py", line 11, in <module>
    from hotsos.plugin_extensions.openstack import (
  File "/snap/hotsos/460/lib/python3.8/site-packages/hotsos/plugin_extensions/openstack/summary.py", line 2, in <module>
    from hotsos.core.plugins.openstack import (
  File "/snap/hotsos/460/lib/python3.8/site-packages/hotsos/core/plugins/openstack/__init__.py", line 14, in <module>
    from hotsos.core.ssl import SSLCertificate
  File "/snap/hotsos/460/lib/python3.8/site-packages/hotsos/core/ssl.py", line 2, in <module>
    from cryptography import x509
  File "/snap/hotsos/460/lib/python3.8/site-packages/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/snap/hotsos/460/lib/python3.8/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/core20/current/lib/x86_64-linux-gnu/librt.so.1)

I have played around with LD_PRELOAD/LD_LIBRARY_PATH to no avail so for now will have the code fail gracefully if the module fails to load to allow eveything else to run.

**Comment by dosaboy** [comment]
re-opening and assigning to @dnegreira who said he would look into the real fix for this

**Comment by nicolasbock** [comment]
Why is it importing from the host?
```
ImportError: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/core20/current/lib/x86_64-linux-gnu/librt.so.1)
```
Or am I misreading this error message?
