### ISSUE TITLE
ssl checks failing with latest snap build

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#360]
2022-06-17 09:50:26,120.120 36686 ERROR None [-] requires.YRequirementTypeProperty.result raised the following
Traceback (most recent call last):
  File "/snap/hotsos/481/lib/python3.8/site-packages/hotsos/core/ycheck/engine/properties.py", line 878, in result
    return self.handler()
  File "/snap/hotsos/481/lib/python3.8/site-packages/hotsos/core/ycheck/engine/properties.py", line 1082, in handler
    actual = self.get_property(path)
  File "/snap/hotsos/481/lib/python3.8/site-packages/hotsos/core/ycheck/engine/properties_common.py", line 226, in get_property
    ret = getattr(cls(), property)
  File "/snap/hotsos/481/lib/python3.8/site-packages/hotsos/core/plugins/openstack/openstack.py", line 188, in apache2_certificates_expiring
    if ssl_checks.certificate_expires_soon:
  File "/snap/hotsos/481/lib/python3.8/site-packages/hotsos/core/host_helpers/ssl.py", line 72, in certificate_expires_soon
    return self.certificate.certificate_days_to_expire <= self.expire_days
  File "/snap/hotsos/481/lib/python3.8/site-packages/hotsos/core/host_helpers/ssl.py", line 44, in certificate_days_to_expire
    certificate_date = self.certificate_expire_date
  File "/snap/hotsos/481/lib/python3.8/site-packages/hotsos/core/host_helpers/ssl.py", line 35, in certificate_expire_date
    default_backend())
  File "/snap/hotsos/481/lib/python3.8/site-packages/cryptography/hazmat/backends/__init__.py", line 14, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/snap/hotsos/481/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/snap/hotsos/481/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 113, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/snap/hotsos/481/lib/python3.8/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_siglongjmp, version GLIBC_PRIVATE

**Comment by dosaboy** [comment]
To mitigate the impact of individual scenarios failing, we now catch the exception and allow the next to run - https://github.com/canonical/hotsos/pull/361

**Comment by dosaboy** [comment]
no longer applies now that we have moved to a confined snap so closing.
