### ISSUE TITLE
Error when saving log file on CIS hardened nodes

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#436]
ubuntu@juju-1f55d6-3-lxd-3:~$ sudo hotsos -s --all-logs
INFO: analysing localhost -
Traceback (most recent call last):
  File "/snap/hotsos/562/bin/hotsos", line 8, in <module>
    sys.exit(main())
  File "/snap/hotsos/562/lib/python3.8/site-packages/hotsos/cli.py", line 296, in main
    cli(prog_name='hotsos')
  File "/snap/hotsos/562/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/snap/hotsos/562/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/snap/hotsos/562/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/hotsos/562/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/snap/hotsos/562/lib/python3.8/site-packages/hotsos/cli.py", line 287, in cli
    path = summary.save(prefix, html_escape=html_escape,
  File "/snap/hotsos/562/lib/python3.8/site-packages/hotsos/client.py", line 329, in save
    os.rename(log.handlers[0].baseFilename,
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp31ou1635hotsos.log' -> 'hotsos-output-1664962390/juju-1f55d6-3-lxd-3/hotsos.log'
-3-lxd-3/hotsos.log'

**Comment by mustafakemalgilor** [comment]
I wonder if this was just a snap-related issue.

**Comment by dosaboy** [comment]
> I wonder if this was just a snap-related issue.

it was, and most probably because of the classic snap which we dont use anymore so I think we can close this now,
