### ISSUE TITLE
Option --user-summary crashes

### ISSUE THREAD

**Issue by joalif** [canonical/hotsos#521]
Hotsos version:
```
jo@t14s:~$ hotsos --version
652
```

Error:
```
jo@t14s:~$ sudo hotsos --user-summary
[sudo] password for jo: 

Traceback (most recent call last):
  File "/snap/hotsos/652/bin/hotsos", line 8, in <module>
    sys.exit(main())
  File "/snap/hotsos/652/lib/python3.8/site-packages/hotsos/cli.py", line 326, in main
    cli(prog_name='hotsos')
  File "/snap/hotsos/652/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/snap/hotsos/652/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/snap/hotsos/652/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/hotsos/652/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/snap/hotsos/652/lib/python3.8/site-packages/hotsos/cli.py", line 297, in cli
    with open(data_root) as fd:
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by dosaboy** [comment]
thanks for the bug, that option should have been deprecated and removed ages ago so im gonna go ahead and do that now.
