### ISSUE TITLE
Test fails if there is .swp file in directory

### ISSUE THREAD

**Issue by joalif** [canonical/hotsos#529]
So not sure if this is a hotsos issue or a vim peculiarity but here it is.
Vim (and maybe other editors) create a .swp file for each window (displaying file) in the file's directory.
Hotsos lists the contents of the test dirs to gather the paths with the tests and excludes only the files 
that end in .disabled.
As a result, if you run the test suite and you happen to have a test file open in vim, hotsos will consider .myrandomtestfile.yaml.swp as a file with tests and will fail the test with the following :

```
Captured traceback:
~~~~~~~~~~~~~~~~~~~
    ImportError: Failed to import test module: tests.unit.test_lxd
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/ubuntu/hotsos/tests/unit/test_lxd.py", line 40, in <module>
    class TestLXDScenarios(LXDTestsBase):
  File "/home/ubuntu/hotsos/tests/unit/utils.py", line 49, in _inner
    tg = TemplatedTestGenerator(path, testdef)
  File "/home/ubuntu/hotsos/tests/unit/utils.py", line 180, in __init__
    self.testdef = yaml.safe_load(open(test_def_path)) or {}
  File "/home/ubuntu/hotsos/.tox/py3/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/ubuntu/hotsos/.tox/py3/lib/python3.10/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
  File "/home/ubuntu/hotsos/.tox/py3/lib/python3.10/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/home/ubuntu/hotsos/.tox/py3/lib/python3.10/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/home/ubuntu/hotsos/.tox/py3/lib/python3.10/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/home/ubuntu/hotsos/.tox/py3/lib/python3.10/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 17: invalid continuation byte
```

This can be fixed with something like [this](https://github.com/canonical/hotsos/commit/506fe0c6c7b6c1d12d177a39af175bc7f981c401
) or maybe by including for testing only  the files that end in .yaml.

Anyway, if you think this is a vim problem feel free to close the issue.

**Comment by dosaboy** [comment]
should be fixed by https://github.com/canonical/hotsos/commit/f7be62a0ee4e55c13b61548dd4895695e1bc5d59
