### ISSUE TITLE
failing to save output on focal

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#667]
Testing the latest Focal daily build gives the following error. This does not happen on Jammy.

ubuntu@hotsos-daily-deb-focal:~$ hotsos -s
INFO: analysing localhost \
Traceback (most recent call last):
  File "/usr/bin/hotsos", line 11, in <module>
    load_entry_point('hotsos===1.15.3.g60b1949b6008-20.04.20230629141711', 'console_scripts', 'hotsos')()
  File "/usr/lib/python3/dist-packages/hotsos/cli.py", line 392, in main
    cli(prog_name='hotsos')
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/hotsos/cli.py", line 383, in cli
    path = summary.save(prefix, html_escape=html_escape,
  File "/usr/lib/python3/dist-packages/hotsos/client.py", line 324, in save
    self._save(path, format, html_escape=html_escape,
  File "/usr/lib/python3/dist-packages/hotsos/client.py", line 290, in _save
    content = self.get(format=format, html_escape=html_escape,
  File "/usr/lib/python3/dist-packages/hotsos/client.py", line 278, in get
    filtered = plugintools.HTMLFormatter(
  File "/usr/lib/python3/dist-packages/hotsos/core/plugintools.py", line 119, in dump
    content = self._expand(data, 1)
  File "/usr/lib/python3/dist-packages/hotsos/core/plugintools.py", line 107, in _expand
    return self._expand_dict(data, level)
  File "/usr/lib/python3/dist-packages/hotsos/core/plugintools.py", line 94, in _expand_dict
    context['dict_elements'][key] = self._expand(value, level + 1)
  File "/usr/lib/python3/dist-packages/hotsos/core/plugintools.py", line 107, in _expand
    return self._expand_dict(data, level)
  File "/usr/lib/python3/dist-packages/hotsos/core/plugintools.py", line 96, in _expand_dict
    return self.render(context, 'content_dict.html')
  File "/usr/lib/python3/dist-packages/hotsos/core/plugintools.py", line 50, in render
    env = Environment(loader=FileSystemLoader(templates_dir))
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable

**Comment by dosaboy** [comment]
not immediately obvious why this is failing since https://jinja.palletsprojects.com/en/2.10.x/api/#jinja2.FileSystemLoader supports a string or list of strings.

**Comment by dosaboy** [comment]
my guess is that the path does not have type str:

```
        if isinstance(path, string_types):
            path = [path]
        else:
            path = list(path)
```
