### ISSUE TITLE
non-unicode chars in sos output causing search to fail

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#718]
I am getting errors like this when analysing a sosreport:

```
2023-09-05 20:31:48,403.403 109393 DEBUG searchkit [-] starting search of dump/sosreport-hostx-2023-07-17-cetemjv/sos_commands/systemd/systemctl_status_--all (offset=0, pos=0)
2023-09-05 20:31:48,427.427 109393 DEBUG searchkit [-] sequence cb1fa446-bc73-4a5a-b055-1b90c6df2719 started section e97c24d2-9b15-4857-a472-3f54f33a6ae1 (completed=0)
2023-09-05 20:31:48,427.427 109393 DEBUG searchkit [-] sequence cb1fa446-bc73-4a5a-b055-1b90c6df2719 stopping section e97c24d2-9b15-4857-a472-3f54f33a6ae1 (completed=1)
2023-09-05 20:31:48,434.434 109393 ERROR searchkit [-] 
Traceback (most recent call last):
  File "/home/user1/.local/pipx/venvs/hotsos/lib/python3.10/site-packages/searchkit/search.py", line 1039, in execute
    fd.read(1)
  File "/usr/lib/python3.10/gzip.py", line 301, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.10/gzip.py", line 488, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.10/gzip.py", line 436, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b'\xe2\x97')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/pipx/venvs/hotsos/lib/python3.10/site-packages/searchkit/search.py", line 1044, in execute
    stats = self._run_search(fd)
  File "/home/user1/.local/pipx/venvs/hotsos/lib/python3.10/site-packages/searchkit/search.py", line 990, in _run_search
    line = line.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 13: invalid continuation byte
2023-09-05 20:31:48,435.435 109393 DEBUG searchkit [-] caught UnicodeDecodeError for path dump/sosreport-hostx-2023-07-17-cetemjv/sos_commands/systemd/systemctl_status_--all - skipping
```

I suspect this is similar to the issue fixed in https://github.com/canonical/hotsos/commit/6c8d361235751b624dd9129d4038b56bb81ecf2c but since we are not searching the contents of sos_commands/systemd/systemctl_status_--all directly the non-unicode chars are still there which causes the searcher to fail.

**Comment by mustafakemalgilor** [comment]
Also, I think the "gzip" traceback is confusing. The problem itself has nothing to do with gzip but still, it's included in the error message. I think the reason why is we're probably invoking non-gzip routine in the catch clause of the gzip handling routine. It would make sense to move that code block out of "catch" to avoid spilling unrelated tracebacks.

**Comment by dosaboy** [comment]
Correct the only issue here is the UnicodeDecodeError, the gzip error is from when it checks if the file is in gzip format and can be ignored.
