### ISSUE TITLE
ovs tunnels detection error

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#762]
Traceback (most recent call last):
  File "/home/ubuntu/.local/pipx/venvs/hotsos/lib/python3.10/site-packages/hotsos/core/plugintools.py", line 394, in run
    output = inst.output
  File "/home/ubuntu/.local/pipx/venvs/hotsos/lib/python3.10/site-packages/hotsos/core/plugintools.py", line 333, in output
    out = getattr(self, m)()
  File "/home/ubuntu/.local/pipx/venvs/hotsos/lib/python3.10/site-packages/hotsos/core/plugintools.py", line 14, in _inner2
    out = f(*args, **kwargs)
  File "/home/ubuntu/.local/pipx/venvs/hotsos/lib/python3.10/site-packages/hotsos/plugin_extensions/openvswitch/summary.py", line 76, in __summary_tunnels
    if self.ovs.tunnels:
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/ubuntu/.local/pipx/venvs/hotsos/lib/python3.10/site-packages/hotsos/core/plugins/openvswitch/ovs.py", line 132, in tunnels
    tunnel_info[proto]['remotes'] = len(tunnel_info[proto]['remotes'])
KeyError: 'remotes'

**Comment by dosaboy** [comment]
in this case the file sos_commands/openvswitch/ovs-appctl_ofproto.list-tunnels was empty
