### ISSUE TITLE
Don't fail on searchkit FileSearchException

### ISSUE THREAD

**Issue by dosaboy** [canonical/hotsos#992]
When searchkit looks for line feeds in a file, it will raise a FileSearchException after reading 1048576 chars and not finding one. We should catch this and move on instead of bailing to allow other searches toi continue:

Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3/dist-packages/searchkit/task.py", line 367, in execute
    raise FileSearchException(msg) from e
searchkit.exception.FileSearchException: an unexpected exception occurred while searching /var/log/juju/machine-34-2024-11-05T08-50-42.450.log.gz - reached max line length (1048576) search without finding a line feed (epicenter=52375442)

**Comment by dosaboy** [comment]
this is now resolved with the [fix in searchkit](https://github.com/dosaboy/searchkit/commit/ea7c05ad843f4bbe748ce4aac4b998ca1a78d919) so closing out.
